server:
  port: 8889

spring:
  application:
    name: Application
  datasource:
    #url: jdbc:h2:./data/test;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/schema.sql
    #data: classpath:/data.sql
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      #database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: false
        path: /h2-console
        settings:
          trace: false
          web-allow-others: false